In [1]:
import os
import json
import pandas as pd

In [5]:
# Table for Top_Transaction data for India State-wise

path = "pulse/data/top/transaction/country/india/state/"

Top_trans = {
    "State":[], "Year":[], "Quarter":[],
    "Entity":[], "Entity_Name":[],
    "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                d = data.get('data', {})

                # STATES (may be null)
                for i in d.get('states') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("State")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

                # DISTRICTS (MAIN DATA)
                for i in d.get('districts') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("District")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

                # PINCODES
                for i in d.get('pincodes') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("Pincode")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

df_Top_trans = pd.DataFrame(Top_trans)
df_Top_trans

,State,Year,Quarter,Entity,Entity_Name,Count,Amount
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,District,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,1,Pincode,744101,1622,2.769298e+06
4,andaman-&-nicobar-islands,2018,1,Pincode,744103,1223,2.238042e+06
...,...,...,...,...,...,...,...
18290,west-bengal,2024,4,Pincode,711101,6753348,1.049483e+10
18291,west-bengal,2024,4,Pincode,700059,6662715,8.009476e+09
18292,west-bengal,2024,4,Pincode,700039,6575693,9.018748e+09
18293,west-bengal,2024,4,Pincode,734001,6432082,8.996529e+09
18294,west-bengal,2024,4,Pincode,733134,6313560,1.050259e+10

In [3]:
# Table for Top_Transaction data for India State-wise

path = "pulse/data/top/transaction/country/india/state/"

Top_trans = {
    "State":[], "Year":[], "Quarter":[],
    "Entity":[], "Entity_Name":[],
    "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                d = data.get('data', {})

                # STATES (may be null)
                for i in d.get('states') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("State")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

                # DISTRICTS (MAIN DATA)
                for i in d.get('districts') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("District")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

                # PINCODES
                for i in d.get('pincodes') or []:
                    Top_trans["State"].append(state)
                    Top_trans["Year"].append(int(year))
                    Top_trans["Quarter"].append(int(file.strip(".json")))
                    Top_trans["Entity"].append("Pincode")
                    Top_trans["Entity_Name"].append(i.get('entityName'))
                    Top_trans["Count"].append(i.get('metric', {}).get('count'))
                    Top_trans["Amount"].append(i.get('metric', {}).get('amount'))

df_Top_trans = pd.DataFrame(Top_trans)
df_Top_trans

,State,Year,Quarter,Entity,Entity_Name,Count,Amount
0,andaman-&-nicobar-islands,2018,1,District,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,District,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,District,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,1,Pincode,744101,1622,2.769298e+06
4,andaman-&-nicobar-islands,2018,1,Pincode,744103,1223,2.238042e+06
...,...,...,...,...,...,...,...
18290,west-bengal,2024,4,Pincode,711101,6753348,1.049483e+10
18291,west-bengal,2024,4,Pincode,700059,6662715,8.009476e+09
18292,west-bengal,2024,4,Pincode,700039,6575693,9.018748e+09
18293,west-bengal,2024,4,Pincode,734001,6432082,8.996529e+09
18294,west-bengal,2024,4,Pincode,733134,6313560,1.050259e+10

In [4]:
# Table for Top_Insurance data for India State-wise

path = "pulse/data/top/insurance/country/india/state/"

Top_ins = {
    "State":[], "Year":[], "Quarter":[],
    "Entity":[], "Entity_Name":[],
    "Count":[], "Amount":[]
}

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):
                file_path = os.path.join(year_path, file)

                with open(file_path, 'r') as f:
                    data = json.load(f)

                d = data.get('data', {})

                # STATES
                for i in d.get('states') or []:
                    Top_ins["State"].append(state)
                    Top_ins["Year"].append(int(year))
                    Top_ins["Quarter"].append(int(file.strip(".json")))
                    Top_ins["Entity"].append("State")
                    Top_ins["Entity_Name"].append(i.get('entityName'))
                    Top_ins["Count"].append(i.get('metric', {}).get('count'))
                    Top_ins["Amount"].append(i.get('metric', {}).get('amount'))

                # DISTRICTS
                for i in d.get('districts') or []:
                    Top_ins["State"].append(state)
                    Top_ins["Year"].append(int(year))
                    Top_ins["Quarter"].append(int(file.strip(".json")))
                    Top_ins["Entity"].append("District")
                    Top_ins["Entity_Name"].append(i.get('entityName'))
                    Top_ins["Count"].append(i.get('metric', {}).get('count'))
                    Top_ins["Amount"].append(i.get('metric', {}).get('amount'))

                # PINCODES
                for i in d.get('pincodes') or []:
                    Top_ins["State"].append(state)
                    Top_ins["Year"].append(int(year))
                    Top_ins["Quarter"].append(int(file.strip(".json")))
                    Top_ins["Entity"].append("Pincode")
                    Top_ins["Entity_Name"].append(i.get('entityName'))
                    Top_ins["Count"].append(i.get('metric', {}).get('count'))
                    Top_ins["Amount"].append(i.get('metric', {}).get('amount'))

df_Top_ins = pd.DataFrame(Top_ins)
df_Top_ins

,State,Year,Quarter,Entity,Entity_Name,Count,Amount
0,andaman-&-nicobar-islands,2020,2,District,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,District,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,2,Pincode,744301,3,565.0
3,andaman-&-nicobar-islands,2020,2,Pincode,744104,2,513.0
4,andaman-&-nicobar-islands,2020,2,Pincode,744101,1,282.0
...,...,...,...,...,...,...,...
12271,west-bengal,2024,4,Pincode,711101,713,750354.0
12272,west-bengal,2024,4,Pincode,700091,642,969634.0
12273,west-bengal,2024,4,Pincode,700150,627,761501.0
12274,west-bengal,2024,4,Pincode,700039,619,787836.0
12275,west-bengal,2024,4,Pincode,700156,574,888613.0